[[main]]
  identifier = "home"
  name = "主页"
  url = "/"
  weight = 1
  [main.params]
    icon = "home"

[[social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/nuomeo"
  
[social.params]
  icon = "brand-github"

[[social]]
  identifier = "bilibili"
  name = "Bilibili"
  url = "https://bilibili.com"
  
[social.params]
  icon = "brand-bilibili"

[[social]]
  identifier = "email"
  name = "邮箱"
  url = "mailto:thalumi@163.com"
[social.params]
  icon = "mail"