[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[[main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 10

[[social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/nuomeo"

[social.params]
  icon = "brand-github"

[[social]]
  identifier = "bilibili"
  name = "Bilibili"
  url = "https://bilibili.com"
