# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
rssFullContent = true
DefaultContentLanguage = "zh-cn"
subtitle = "Keep Doing"

[contact]
email = "thalumi@163.com"

[footer]
since = 2025
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[sidebar.compact]
enabled = true

[article]
headingAnchor = false
math = false
readingTime = true

[[widgets.page]]
type = "toc"

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[[widgets.homepage]]
type = "categories"

[[widgets.homepage]]
type = "tag-cloud"

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"
