baseURL = "https://nuomeo.github.io"
languageCode = "en"
title = "镜花水月"
theme = "hugo-theme-stack"
author = "nuomeo"
[params]
  subtitle = 'Keep Doing'
  [params.contact]
    email = 'thalumi@163.com'

[pagination]
pagerSize = 15
